### ISSUE TITLE
Task 2 (Mockups)

### ISSUE THREAD

**Issue by ala-n** [glebek2h/instagram-brother#2]
Almost all things are correct now.
The only things missing are:
[-] A detailed description of tag input field
[-] Some clarity in filters logic
I propse here to do the following: 
 1. remove the unnecessary filter toggle
 2. Add a link-like button "FIlter by date..." instead, that triggers the date filter area that you already have in the wireframe
 3. Mark your smart search input by some comment/label and make a separate detailed view for just that input field.
 4. Carefuly and explicitly describe diferent states and behaviour of that field.

Current mark is 8 (with a little + :) ) if you make a detailed wireframe for "smart" tag/name input it will be 10.

**Comment by glebek2h** [comment]
New version is ready ;)

**Comment by ala-n** [comment]
Nice enough )
You have 10 now. Thanks!
