### ISSUE TITLE
Задание №4

### ISSUE THREAD

**Issue by alexey-kozlenkov** [glebek2h/instagram-brother#3]
1. Используйте тернарный оператор для короткой записи таких веток 
```
if (count !== 0 && count === configTags.length) {
  return true;
}
return false;
```
2. В методе `addPhotoPost` можно переиспользовать метод `getPhotoPost `
3. В методе `editPhotoPost` излишня двойная итерация по всему массиву (`findIndex` + `getPhotoPost `)
4. Внутри `for ... in` циклов нужно делать проверку на `hasOwnProperty`

**Comment by glebek2h** [comment]
New version is ready
