### ISSUE TITLE
Task 3 (HTML + CSS)

### ISSUE THREAD

**Issue by ala-n** [glebek2h/instagram-brother#4]
[-] form class="search" 
 search - isn't saning much about what it really is, better search-form or something like that
 names of fields inside the form shouldn't be empty, for input it's required., for button name attribute is not needed
[-] `<button id = "show-more"><span>show more...</span></button>` etc - span is redundant I think
[=] 
```
<p class = "tags-block"><b>hashtags</b> <a href="">#famcs</a> <a href="">#bsu</a> <a href="">#programming</a> <a href="">#glebogram</a>
                    </p>
```
semantically it's a list, so better
```
<div class="label">hashtags</div>
<ul class = "tags-block"> 
   <li><a href="">#famcs</a></li>
   <li> <a href="">#bsu</a> </li>
   <li> <a href="">#programming</a> </li> 
    <li><a href="">#glebogram</a></li>
</ul>
```
[-] do not use <b> outside of preformated text, beter use CSS font-weight
[=] Interesting thing `<h1 class = "site-name"> glebogram </h1>` isn't ok semantically in the footer, but what the alternative it's interesting question, mb semantic-less div.
[=] better move `<button id = "show-more"><span>show more...</span></button>` outside of 'wrapper', that basically better to call 'post-container', that will save your time in the future.

Generally not bed, just much  semantic problems and typography tegs in markup
Current mark is 8 with -

**Comment by glebek2h** [comment]
New version is ready;)
